# This file is machine-generated - editing it directly is not advised

julia_version = "1.12.2"
manifest_format = "2.0"
project_hash = "de10579cc1fef9501da328125491d6410ede62a5"

[[deps.TVMultiSARMA]]
path = "."
uuid = "c829f553-22ac-4b19-a1dc-cc178927e19e"
version = "1.0.0-DEV"
