name = "TVMultiSARMA"
uuid = "c829f553-22ac-4b19-a1dc-cc178927e19e"
version = "1.0.0-DEV"
authors = ["Mattias Villani", "Ganna Fagerberg"]

[deps]
BandedMatrices = "aae01518-5342-5314-be14-df237901396f"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
DynamicGlobalLocalShrinkage = "95f0ba86-bb51-4e4e-bc21-89dc4565d801"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
LaTeXStrings = "b964fa9f-0449-5b57-a5c2-d3ea65f4040f"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Measures = "442fdcdd-2543-5da2-b0f3-8c86c306513e"
PDMats = "90014a1f-27ba-587c-ab20-58faa44d9150"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Polynomials = "f27b6e38-b328-58d1-80ce-0feddd5e7a45"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
SMCsamplers = "2328efba-24c2-4a10-a32f-a74f69d05fca"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
TimeSeriesUtils = "20aa821e-5b1c-4f19-affd-90757a4fca77"
Utils = "a6a4a4df-ba9f-45e9-bafc-bec3296762b9"

[sources]
DynamicGlobalLocalShrinkage = {rev = "main", url = "https://github.com/mattiasvillani/DynamicGlobalLocalShrinkage.jl.git"}
SMCsamplers = {rev = "main", url = "https://github.com/mattiasvillani/SMCsamplers.jl.git"}
TimeSeriesUtils = {rev = "main", url = "https://github.com/mattiasvillani/TimeSeriesUtils.jl.git"}
Utils = {rev = "main", url = "https://github.com/mattiasvillani/Utils.jl.git"}

[compat]
BandedMatrices = "1.10.2"
Distributions = "0.25.122"
DynamicGlobalLocalShrinkage = "1.0.0"
ForwardDiff = "1.3.0"
JLD2 = "0.6.3"
LaTeXStrings = "1.4.0"
LinearAlgebra = "1.12.0"
Measures = "0.3.3"
PDMats = "0.11.36"
Plots = "1.41.1"
Polynomials = "4.1.0"
ProgressMeter = "1.11.0"
Random = "1.11.0"
Revise = "3.12.3"
SMCsamplers = "1.0.0"
Statistics = "1.11.1"
TimeSeriesUtils = "1.0.0"
Utils = "0.1.0"
julia = "1.12"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
