name = "TVMultiSARMA"
uuid = "c829f553-22ac-4b19-a1dc-cc178927e19e"
authors = ["Mattias Villani", "Ganna Fagerberg"]
version = "1.0.0-DEV"

[compat]
julia = "1.12"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
