[deps]
DSP = "717857b8-e6f2-59f4-9121-6e50c889abd2"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
LaTeXStrings = "b964fa9f-0449-5b57-a5c2-d3ea65f4040f"
Literate = "98b081ad-f1c9-55d3-8b20-4c87d4299306"
Measures = "442fdcdd-2543-5da2-b0f3-8c86c306513e"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
TVMultiSARMA = "c829f553-22ac-4b19-a1dc-cc178927e19e"
TimeSeriesUtils = "20aa821e-5b1c-4f19-affd-90757a4fca77"
Utils = "a6a4a4df-ba9f-45e9-bafc-bec3296762b9"

[sources]
TVMultiSARMA = {path = "/home/mv/Dropbox/Julia/dev/TVMultiSARMA/docs/.."}
TimeSeriesUtils = {rev = "main", url = "https://github.com/mattiasvillani/TimeSeriesUtils.jl.git"}
Utils = {rev = "main", url = "https://github.com/mattiasvillani/Utils.jl.git"}
